### ISSUE TITLE
add example of how to use this lib with oauth2

### ISSUE THREAD

**Issue by shdunning** [rbriski/atlassian-jwt#1]
I'm currently looking at how, or if i need, to use this in conjunction with `golang.org/x/oauth2/jira` and i'm getting stuck here:

```
import (
  "golang.org/x/oauth2"
  "golang.org/x/oauth2/jira"
)
...
	o := oauth2.Config{oauthClientId, sharedSecret, oauth2.Endpoint{jiraAuthURL, tokenURL}, "", []string{"READ"}}
	c := jira.Config{instanceURL, userKey, o}
	client := c.Client(??) // <-- needs a context.Context???
```

How do I get from a starting state of I'm past the install point and I just need to get a bearer token?

**Comment by shdunning** [comment]
Further, it seems like other oauth2 clients use the `Exchange` method to get access_token (so it can be cached i'm guessing), but when I try to use the `Exchange` method in Jira I get an unsupported grant type error: `Unsupported grant type 'authorization_code'`.

**Comment by shdunning** [comment]
Ok, I got something working-ish -- but the jira auth server doesn't like the scopes param b/c it's being prepended with a bunch of `+` chars:

```Response: {"error":"invalid_scope","error_description":"Invalid scopes: ++++ACT_AS_USER+READ+WRITE+ADMIN"}```

Code:

```
	o := oauth2.Config{oauthClientId, string(sharedSecret), oauth2.Endpoint{jiraAuthURL, tokenURL}, "", []string{"ACT_AS_USER","READ","WRITE","ADMIN"}}
	c := jira.Config{instanceURL, userKey, o}
	ts := c.TokenSource(context.Background())
	token, err := ts.Token()
	if err != nil {
		fmt.Println("error getting access token=", err)
		panic(err)
	}
	fmt.Printf("access token=%s\n\n", token)```

If I omit scopes (i.e., set them to `nil`), then I get back a valid access_token.

**Comment by shdunning** [comment]
@rbriski still no dice -- i just tried your suggestion and got a 403 when doing an issue GET. More details in a minute...

**Comment by shdunning** [comment]
userKey := "urn:atlassian:connect:userkey:admin"

**Comment by shdunning** [comment]
Oh, I changed userKey = `"admin"` and it worked:

```
eq= GET /rest/api/2/issue/TESTY-1 HTTP/1.1
Host: shaund.atlassian.net
Content-Type: application/json


Req Headers: map[Content-Type:[application/json]]
Issue: &{Expand:renderedFields,names,schema,operations,editmeta,changelog,versionedRepresentations ID:10000 Self:https://shaund.atlassian.net/rest/api/2/issue/10000 Key:TESTY-1 Fields:0xc420178d80 Changelog:<nil>}```

**Comment by shdunning** [comment]
This is looking good. 

M next question: how do I get / set the access token if we want caching across session / processes? Since the tokens expire after 15 min, this might be a moot point. However previously, in my other PR, we were able get / set the token via func call and we stored the token in redis with a generous expiration (to optimize for bursts of activity within a timeframe).

**Comment by rbriski** [comment]
You shouldn’t need to mess with refreshing the token. The oauth2 library
handles that for you automatically.

As long as you have the data that the install process returns the library
takes care of the rest.

**Comment by shdunning** [comment]
> You shouldn’t need to mess with refreshing the token. The oauth2 library
handles that for you automatically.

I'd imagine it would handle intra-process token refreshing just fine, but I was hoping to gain benefits of caching across processes (hence redis). Without access to some storage (or some IPC magic) I don't see how the oauth2 library can help with reusing tokens across (web handler) processes.

All that being said, I don't think this is a big deal at this time and might have been a pre-optimization on my part. You can close this issue out when https://github.com/rbriski/atlassian-jwt/pull/2 is merged -- that helped a lot!

**Comment by jef** [comment]
Hey @rbriski,

This doesn't seem like the greatest place to ask, but perhaps the most relevant.

I've created an app via https://developer.atlassian.com/ and have been trying to get a working JWT/OAuth token. I cannot seem to figure out how this dance works. When creating the app, I pointed the callback to `http://localhost:8080/api/v1/jira/auth` for testing purposes.

When I install the app, I get something like this returned to me: `http://localhost:8080/api/v1/jira/auth?code={someCode}&state={theOriginalUserBoundValue}`

A few questions:

- Is the `code` query param used for `ClientSecret`?
- What do I give for the `ClientID`?
- What do I give for the `Subject`?
- What do I give for the user bound value?

I don't seem to get any of the `SecurityContext` that the example is alluding to.

Here is the basic implementation that I have using your implementation from https://golang.org/x/oauth2/jira:

```golang
func getClient(c *fiber.Ctx) error {
	jc := &jiraJwt.Config{
		BaseURL: "https://<company>.atlassian.net",
		Subject: "<someSubject>",
		Config:  oauth2.Config{
			ClientID:     "<someClientId>",
			ClientSecret: "<someClientSecret>",
			Endpoint:     oauth2.Endpoint{
				AuthURL: "https://auth.atlassian.io",
				TokenURL: "https://auth.atlassian.io/oauth2/token",
			},
		},
	}

	jiraClient, _ = jira.NewClient(jc.Client(c.Context()), jc.BaseURL)
	user, res, err := jiraClient.User.GetSelf()

	log.Info().Msgf("%v", user)
	log.Info().Msgf("%v", res)
	log.Info().Msgf("%v", err)

	err = c.SendString("OK")
	return err
}
```

I get this reponse:

```
No response returned: Get \"https://<company>.atlassian.net/rest/api/2/myself\": oauth2: cannot fetch token: 400 Bad Request\nResponse: {\"error\":\"invalid_request\",\"error_description\":\"No oauth client details found for https://<company>.atlassian.net and oauthClientId <someClientId>\"}"
```

![image](https://user-images.githubusercontent.com/12074633/107133937-77063280-68bb-11eb-84d8-7c6431c850e1.png)

Are the ID and Secret here given for the app?

Obviously this is not how I want to persist any of the client information, but I wanted to get a working example as a minimum first and I can't seem to break past this point.

Are you able to help point me in the right direction? I hate to ask here, but it seems that you two have been quite intimate with their API and I'm not completely following it.

Thanks!

**Comment by rbriski** [comment]
Awesome! Also, you should head on over to https://github.com/golang-jwt/jwt where the maintained version of this library lives.
