### ISSUE TITLE
Upgrate `dgrijalva/jwt-go` to `golang-jwt` to v4 or v5

### ISSUE THREAD

**Issue by choznerol** [rbriski/atlassian-jwt#4]
Thank you for creating this package.
This package uses [`dgrijalva/jwt-go`](https://github.com/dgrijalva/jwt-go), which was now archived and moved to [`golang-jwt/jwt`](https://github.com/golang-jwt/jwt). `golang-jwt/jwt` v4 should be a [drop-in replacement](https://github.com/golang-jwt/jwt/blob/main/MIGRATION_GUIDE.md#migration-guide-v400), while `golang-jwt` v5 needs some [minor change](https://github.com/golang-jwt/jwt/blob/main/MIGRATION_GUIDE.md#migration-guide-v500) to custom claim usage.

With the changes introduced in `golang-jwt` v5, this package is currently incompatible with a project using `golang-jwt` v5. I can help create a PR if this update is desired.

**Comment by hanzei** [comment]
@rbriski Would you be open to accepting a PR that migrates the code to `golang-jwt`?

**Comment by rbriski** [comment]
Sure, let me know what you need from me.

**Comment by hanzei** [comment]
Submitted https://github.com/rbriski/atlassian-jwt/pull/5. @rbriski Please take a look.
